"""
Feature selection tests on the features generated by features.py
How many features do we need to reach *ok* classification?
"""

def forward_select(features):
    """
    features - pd.DataFrame with features in columns and labels in the index 
    reutrn the order of selection and preformance for each step.
    """
    



