"""
Feature selection tests on the features generated by features.py
How many features do we need to reach *ok* classification?
"""

import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.cross_validation import KFold


def forward_select(features, num_features=20, num_splits = 3):
    """
    features - pd.DataFrame with features in columns and labels in the index.
    num_features - the number of features to select.
    num_splits - the number of splits for the cross validation procedure on each step.
    reutrn the order of selection and preformance for each step.
    """
    clf = SVC(kernel='linear')
  
    f_selected = []
    f_unselected = set(features.columns.values)
    p_correct = []
    
    for nFeatures in range(num_features): 
        # find and select the next best feature
        current_score = -np.inf
        current_feature = None
        
        for current in f_unselected:
            
            #print("Current feature: ", current)

            # current data view 
            data = features[f_selected + [current]]

            # cross validation
            score = []
            for train_idx, test_idx in KFold(data.shape[0], n_folds = num_splits, shuffle=True):
                clf.fit(data.iloc[train_idx], data.iloc[train_idx].index.values)
                out = clf.predict(data.iloc[test_idx])
                out = (out == data.iloc[test_idx].index.values).mean()
                score.append(out)
            score = np.mean(score)

            # update 
            if score>current_score: 
                current_score = score
                current_feature = current 

        f_unselected.remove(current_feature)
        f_selected.append(current_feature)
        p_correct.append(current_score)

    return pd.Series(p_correct, f_selected)



if __name__ == "__main__":
    """ Test the feature selection tool """
    from sklearn.datasets.samples_generator import make_classification
    data, labels = make_classification(n_samples=100, n_features=20, n_informative=10, n_redundant=10, n_classes=4, n_clusters_per_class=2, class_sep=10, hypercube=False)
    data = pd.DataFrame(data, index=labels)
    
    selection = forward_select(data, num_features=20, num_splits=2)
    print(selection)



