"""
...

"""

def compare_partitions(original_partiton, new_partition, method):
    """
    Used to compare the supervised partition of the ACC data to the partition 
    generated by one of the clustering methods. 
    """
    return 0



